services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    networks:
      - healthify
    depends_on:
      - backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    networks:
      - healthify
    depends_on:
      - db
      - redis
      - gen-ai
  gen-ai:
    build: 
      context: ./GenAI
      dockerfile: Dockerfile
    networks:
      - healthify
  db:
    build:
      context: ./backend/db_design
      dockerfile: Dockerfile
    networks:
      - healthify
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=healthify
    volumes:
      - healthify:/var/lib/mysql
  redis:
    image: redis/redis-stack:latest
    ports:
      - "3001:8001"
    networks:
      - healthify

networks:
  healthify:
    driver : bridge
volumes:
  healthify: